// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBue2BkjtSwzTvxj2nffXdpoUEk3mY_3aE',
    appId: '1:205028620562:web:e12449045b3bd19b5adbcb',
    messagingSenderId: '205028620562',
    projectId: 'fir-flutter-codelab-a3fb3',
    authDomain: 'fir-flutter-codelab-a3fb3.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-a3fb3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgaU7xqlDmSOg4z2oF1m9K6TaLH3A9new',
    appId: '1:205028620562:android:8ea6b2020d878e455adbcb',
    messagingSenderId: '205028620562',
    projectId: 'fir-flutter-codelab-a3fb3',
    storageBucket: 'fir-flutter-codelab-a3fb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByVQbfkfp8LityTW0fSXn6rn2dp7uip64',
    appId: '1:205028620562:ios:2cfc6e9df66121cc5adbcb',
    messagingSenderId: '205028620562',
    projectId: 'fir-flutter-codelab-a3fb3',
    storageBucket: 'fir-flutter-codelab-a3fb3.appspot.com',
    iosClientId: '205028620562-otvpt60rae3skgo3sjcta8encd8q9blf.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByVQbfkfp8LityTW0fSXn6rn2dp7uip64',
    appId: '1:205028620562:ios:2cfc6e9df66121cc5adbcb',
    messagingSenderId: '205028620562',
    projectId: 'fir-flutter-codelab-a3fb3',
    storageBucket: 'fir-flutter-codelab-a3fb3.appspot.com',
    iosClientId: '205028620562-otvpt60rae3skgo3sjcta8encd8q9blf.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
